name: weather
description: Weather application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state manager
  provider: ^6.0.3

  # di
  get_it: ^7.2.0

  # router
  go_router: ^4.1.0

  # local storage
  shared_preferences: ^2.0.15

  # localization
  easy_localization: ^3.0.1

  # network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  # location
  geolocator: ^9.0.1
  geocoding: ^2.0.4

  # ui
  fluttertoast: ^8.0.9

  # utils
  url_strategy: ^0.2.0
  url_launcher: ^6.1.4
  universal_html: ^2.0.8
  package_info_plus: ^1.4.2
  connectivity_plus: ^2.3.5
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  web: false
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: '#3AB472'
  image_path: 'assets/png/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/translations/
